db:  
  image: index.tenxcloud.com/tenxcloud/postgres:latest 
web:  
  build: .  
  command: python manage.py runserver 0.0.0.0:8887  
  volumes:  
    - .:/code  
  ports:  
    - "8887:8887"  
  links:  
    - db 
